services:
  notificaciones-svc:
    build: .
    image: duoc/jv0101-foodgo-notificaciones:1.0.0
    container_name: foodgo-notificaciones-svc
    ports:
      - "${PORT:-8086}:8086"
    restart: unless-stopped
